=====================================================================
# <font size = 5 color='Black'><u>Employee Wellness Prediction using Logistic Regression<u> 
=====================================================================

## Abstract

Take care of your employees: A drastic thing happened and ABCXYZ123 Technical Solutions have lost one of their important employees. The company is now very concerned about the health of their employees and would want you to find that set of employees who are in need or may be in need of treatment, taking into account multiple attributes that are already stored in the database. So buckle up the wellness of your employees is in your hand.

## Problem Statement

The objective is to predict values “treatment” attribute from the given features of the Test data.

## Data Description

• Timestamp

• Age

• Gender

• Country

• state -> If you live in the United States, which state or territory do you live in?

• self_employed -> Are you self-employed?

• family_history -> Do you have a family history of mental illness?

• work_interfere -> If you have a mental health condition, do you feel that it interferes with your work?

• no_employees -> How many employees does your company or organization have?

• remote_work -> Do you work remotely (outside of an office) at least 50% of the time?

• tech_company -> Is your employer primarily a tech company/organization?

• benefits -> Does your employer provide mental health benefits?

• care_options -> Do you know the options for mental health care your employer provides?

• wellness_program -> Has your employer ever discussed mental health as part of an employee wellness program?

• seek_help -> Does your employer provide resources to learn more about mental health issues and how to seek help?

• anonymity -> Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources?

• leave -> How easy is it for you to take medical leave for a mental health condition?

• mental_health_consequence -> Do you think that discussing a mental health issue with your employer would have negative consequences?

• phys_health_consequence -> Do you think that discussing a physical health issue with your employer would have negative consequences?

• coworkers -> Would you be willing to discuss a mental health issue with your coworkers?

• supervisor -> Would you be willing to discuss a mental health issue with your direct supervisor(s)?

• mental_health_interview -> Would you bring up a mental health issue with a potential employer in an interview?

• phys_health_interview -> Would you bring up a physical health issue with a potential employer in an interview?

• mental_vs_physical -> Do you feel that your employer takes mental health as seriously as physical health?

• obs_consequence -> Have you heard of or observed negative consequences for coworkers with mental health conditions in your workplace?

• comments -> Any additional notes or comments.

• treatment -> Does he or she really needs treatment.

=====================================================================

### Importing Necessary Libraries

In [1]:
#to hide warnings
import warnings
warnings.filterwarnings("ignore")

In [2]:
#for working with arrays
import numpy as np
#for reading data and other manipulations
import pandas as pd
#for visulaization
import matplotlib.pyplot as plt
import seaborn as sns
#for encoding categorical variables
from sklearn.preprocessing import LabelEncoder
#for scaling the data
from sklearn.preprocessing import StandardScaler
#for splitting the data into train set ans test set
from sklearn.model_selection import train_test_split
#for performing Linear regression and other regularization techniques
from sklearn.linear_model import LogisticRegression
#for model evaluation
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
#for performing Stochastic Gradient Descent Classification
from sklearn.linear_model import SGDClassifier
#for feature selection
from sklearn.feature_selection import RFE
#for kfold cross validation
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

### Reading data

In [3]:
#Creating a dataframe for train data
data = pd.read_csv(r"C:/Users/shree/Desktop/bhavika ml/ClassifierDataSet/training_.csv",header = 0,delimiter = ',')
#Creating a dataframe for test data
test_data = pd.read_csv(r"C:/Users/shree/Desktop/bhavika ml/ClassifierDataSet/test.csv",header = 0,delimiter = ',')

In [4]:
#to display all the columns and intended rows on the screen
pd.set_option('display.max_columns',None)
#to check the sample data
data.head()

,S.No,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,1,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,No,Yes,Yes,Not sure,No,Yes,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,No,No,Don't know,No,Don't know,Don't know,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,3,2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,No,Yes,No,No,No,No,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,4,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,No,Yes,No,Yes,No,No,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,5,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,Yes,Yes,Yes,No,Don't know,Don't know,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN

In [5]:
test_data.head()

,S.No,Timestamp,Age,Gender,Country,state,self_employed,family_history,work_interfere,no_employees,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,1,2014-08-29 11:32:22,39,Male,United Kingdom,NaN,Yes,Yes,Sometimes,1-5,Yes,Yes,No,Yes,Yes,Yes,Yes,Somewhat difficult,No,No,Yes,Yes,No,Maybe,Yes,Yes,These result may be a tad confusing so a summa...
1,2,2014-08-29 11:32:44,26,female,United States,WA,No,Yes,Sometimes,More than 1000,No,Yes,Yes,Yes,No,No,Don't know,Don't know,No,No,Some of them,Yes,No,Maybe,No,Yes,I should note one of the places my employer fa...
2,3,2014-08-29 11:33:54,23,Female,United States,IL,No,Yes,Sometimes,26-100,No,No,No,No,No,No,Don't know,Somewhat difficult,Yes,No,No,Some of them,No,Maybe,No,No,NaN
3,4,2014-08-29 11:34:07,35,Male,Switzerland,NaN,No,Yes,Often,More than 1000,No,Yes,Don't know,Not sure,No,No,Yes,Very easy,No,No,Some of them,Some of them,No,Maybe,No,No,NaN
4,5,2014-08-29 11:36:38,36,Male,United States,FL,No,No,Never,1-5,Yes,Yes,Don't know,Not sure,Don't know,Don't know,Don't know,Very easy,No,No,Some of them,Some of them,No,No,Don't know,No,NaN

### Understanding the data

In [6]:
data.shape

(1048, 28)

Data has 1048 observation and 28 columns out of which 1 column has Dependent variable and other 27 are Independent var

In [7]:
data.columns

Index(['S.No', 'Timestamp', 'Age', 'Gender', 'Country', 'state',
       'self_employed', 'family_history', 'treatment', 'work_interfere',
       'no_employees', 'remote_work', 'tech_company', 'benefits',
       'care_options', 'wellness_program', 'seek_help', 'anonymity', 'leave',
       'mental_health_consequence', 'phys_health_consequence', 'coworkers',
       'supervisor', 'mental_health_interview', 'phys_health_interview',
       'mental_vs_physical', 'obs_consequence', 'comments'],
      dtype='object')

In [8]:
data.dtypes

S.No                          int64
Timestamp                    object
Age                           int64
Gender                       object
Country                      object
state                        object
self_employed                object
family_history               object
treatment                    object
work_interfere               object
no_employees                 object
remote_work                  object
tech_company                 object
benefits                     object
care_options                 object
wellness_program             object
seek_help                    object
anonymity                    object
leave                        object
mental_health_consequence    object
phys_health_consequence      object
coworkers                    object
supervisor                   object
mental_health_interview      object
phys_health_interview        object
mental_vs_physical           object
obs_consequence              object
comments                     object
dtype: object

we can see that most of the variables are categorical variables

In [9]:
#to get insights from data by looking at their mean,std etc.,
data.describe(include = 'all')

,S.No,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
count,1048.000000,1048,1.048000e+03,1048,1048,636,1030,1048,1048,812,1048,1048,1048,1048,1048,1048,1048,1048,1048,1048,1048,1048,1048,1048,1048,1048,1048,132
unique,NaN,1035,NaN,45,42,45,2,2,2,4,6,2,2,3,3,3,3,3,5,3,3,3,3,3,3,3,2,128
top,NaN,2014-08-27 15:55:07,NaN,Male,United States,CA,No,No,No,Sometimes,6-25,No,Yes,Yes,No,No,No,Don't know,Don't know,No,No,Some of them,Yes,No,Maybe,Don't know,No,* Small family business - YMMV.
freq,NaN,2,NaN,518,644,123,906,643,536,386,245,733,870,400,422,692,534,685,466,424,773,651,439,835,461,471,902,5
mean,524.500000,NaN,9.541988e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,302.675844,NaN,3.089010e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,NaN,-1.726000e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,262.750000,NaN,2.700000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,524.500000,NaN,3.100000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,786.250000,NaN,3.600000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1048.000000,NaN,1.000000e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048 entries, 0 to 1047
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   S.No                       1048 non-null   int64
 1   Timestamp                  1048 non-null   object
 2   Age                        1048 non-null   int64
 3   Gender                     1048 non-null   object
 4   Country                    1048 non-null   object
 5   state                      636 non-null    object
 6   self_employed              1030 non-null   object
 7   family_history             1048 non-null   object
 8   treatment                  1048 non-null   object
 9   work_interfere             812 non-null    object
 10  no_employees               1048 non-null   object
 11  remote_work                1048 non-null   object
 12  tech_company               1048 non-null   object
 13  benefits                   1048 non-null   object
 14  care_options               1048 non-null   object
 15  wellness_program           1048 non-null   object
 16  seek_help                  1048 non-null   object
 17  anonymity                  1048 non-null   object
 18  leave                      1048 non-null   object
 19  mental_health_consequence  1048 non-null   object
 20  phys_health_consequence    1048 non-null   object
 21  coworkers                  1048 non-null   object
 22  supervisor                 1048 non-null   object
 23  mental_health_interview    1048 non-null   object
 24  phys_health_interview      1048 non-null   object
 25  mental_vs_physical         1048 non-null   object
 26  obs_consequence            1048 non-null   object
 27  comments                   132 non-null    object
dtypes: int64(2), object(26)
memory usage: 229.4+ KB

As per the Non-Null Count, we can see there are a lot of missing values in some columns like state, work_interfere and comments

In [11]:
# to check for the unique values in all the variables to understand the data
#we do not want unique values for timestamp and comments because they are going to be enormous
for i in data.columns:
    if i != 'Timestamp' and i != 'comments':
        print("COLUMN: ", i.upper())
        print("")
        print(data[i].unique())
        print("")

COLUMN:  S.NO

[   1    2    3 ... 1046 1047 1048]

COLUMN:  AGE

[         37          44          32          31          33          35
          39          42          23          29          36          27
          46          41          34          30          40          38
          50          24          18          28          26          22
          19          25          45          21         -29          43
          56          60          54         329          55 99999999999
          48          20          57          58          47          62
          51          65          49       -1726           5          53
          61           8]

COLUMN:  GENDER

['Female' 'M' 'Male' 'male' 'female' 'm' 'Male-ish' 'maile' 'Trans-female'
 'Cis Female' 'F' 'something kinda male?' 'Cis Male' 'Woman' 'f' 'Mal'
 'Male (CIS)' 'queer/she/they' 'non-binary' 'Femake' 'woman' 'Make' 'Nah'
 'All' 'Enby' 'fluid' 'Genderqueer' 'Female ' 'Androgyne' 'Agender'
 'cis-female/femme' 'Guy (-ish) ^_^' 'male leaning androgynous' 'Male '
 'Man' 'Trans woman' 'msle' 'Neuter' 'Female (trans)' 'queer'
 'Female (cis)' 'Mail' 'cis male' 'A little about you' 'Malr']

COLUMN:  COUNTRY

['United States' 'Canada' 'United Kingdom' 'Bulgaria' 'France' 'Portugal'
 'Netherlands' 'Switzerland' 'Poland' 'Australia' 'Germany' 'Russia'
 'Mexico' 'Brazil' 'Slovenia' 'Costa Rica' 'Austria' 'Ireland' 'India'
 'South Africa' 'Italy' 'Sweden' 'Colombia' 'Latvia' 'Romania' 'Belgium'
 'New Zealand' 'Zimbabwe' 'Spain' 'Finland' 'Uruguay' 'Israel'
 'Bosnia and Herzegovina' 'Hungary' 'Singapore' 'Japan' 'Nigeria'
 'Croatia' 'Norway' 'Thailand' 'Denmark' 'Bahamas, The']

COLUMN:  STATE

['IL' 'IN' nan 'TX' 'TN' 'MI' 'OH' 'CA' 'CT' 'MD' 'NY' 'NC' 'MA' 'IA' 'PA'
 'WA' 'WI' 'UT' 'NM' 'OR' 'FL' 'MN' 'MO' 'AZ' 'CO' 'GA' 'DC' 'NE' 'WV'
 'OK' 'KS' 'VA' 'NH' 'KY' 'AL' 'NV' 'NJ' 'SC' 'VT' 'SD' 'ID' 'MS' 'RI'
 'WY' 'LA' 'ME']

COLUMN:  SELF_EMPLOYED

[nan 'Yes' 'No']

COLUMN:  FAMILY_HISTORY

['No' 'Yes']

COLUMN:  TREATMENT

['Yes' 'No']

COLUMN:  WORK_INTERFERE

['Often' 'Rarely' 'Never' 'Sometimes' nan]

COLUMN:  NO_EMPLOYEES

['6-25' 'More than 1000' '26-100' '100-500' '1-5' '500-1000']

COLUMN:  REMOTE_WORK

['No' 'Yes']

COLUMN:  TECH_COMPANY

['Yes' 'No']

COLUMN:  BENEFITS

['Yes' "Don't know" 'No']

COLUMN:  CARE_OPTIONS

['Not sure' 'No' 'Yes']

COLUMN:  WELLNESS_PROGRAM

['No' "Don't know" 'Yes']

COLUMN:  SEEK_HELP

['Yes' "Don't know" 'No']

COLUMN:  ANONYMITY

['Yes' "Don't know" 'No']

COLUMN:  LEAVE

['Somewhat easy' "Don't know" 'Somewhat difficult' 'Very difficult'
 'Very easy']

COLUMN:  MENTAL_HEALTH_CONSEQUENCE

['No' 'Maybe' 'Yes']

COLUMN:  PHYS_HEALTH_CONSEQUENCE

['No' 'Yes' 'Maybe']

COLUMN:  COWORKERS

['Some of them' 'No' 'Yes']

COLUMN:  SUPERVISOR

['Yes' 'No' 'Some of them']

COLUMN:  MENTAL_HEALTH_INTERVIEW

['No' 'Yes' 'Maybe']

COLUMN:  PHYS_HEALTH_INTERVIEW

['Maybe' 'No' 'Yes']

COLUMN:  MENTAL_VS_PHYSICAL

['Yes' "Don't know" 'No']

COLUMN:  OBS_CONSEQUENCE

['No' 'Yes']

We can see that we need to encode all the categorical variables to discrete/numerical variables

And we also noticed that some values of age like 99999999999,329,-1726,-29 are totally inaccurate and we should handle them

### Data Preprocessing

# <font size = 3 color='Black'><b>1). Feature Selection</b>

We can drop the insignificant independent variableby using domain specific knowledge

In this data, Sno,Timestamp,comments,country,state does not have any significance with respect to predictiong wellness of employees

In [12]:
#we'll drop the data from the copy of dataframe to keep the original data intact
df = data.drop(['S.No', 'Timestamp','Country', 'state','comments'], axis =1)
#will apply same to the test data
df_test = test_data.drop(['S.No', 'Timestamp','Country', 'state','comments'], axis =1)

In [13]:
df.head()

,Age,Gender,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37,Female,NaN,No,Yes,Often,6-25,No,Yes,Yes,Not sure,No,Yes,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,44,M,NaN,No,No,Rarely,More than 1000,No,No,Don't know,No,Don't know,Don't know,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
2,32,Male,NaN,No,No,Rarely,6-25,No,Yes,No,No,No,No,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
3,31,Male,NaN,Yes,Yes,Often,26-100,No,Yes,No,Yes,No,No,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
4,31,Male,NaN,No,No,Never,100-500,Yes,Yes,Yes,No,Don't know,Don't know,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No

In [14]:
df_test.head()

,Age,Gender,self_employed,family_history,work_interfere,no_employees,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,39,Male,Yes,Yes,Sometimes,1-5,Yes,Yes,No,Yes,Yes,Yes,Yes,Somewhat difficult,No,No,Yes,Yes,No,Maybe,Yes,Yes
1,26,female,No,Yes,Sometimes,More than 1000,No,Yes,Yes,Yes,No,No,Don't know,Don't know,No,No,Some of them,Yes,No,Maybe,No,Yes
2,23,Female,No,Yes,Sometimes,26-100,No,No,No,No,No,No,Don't know,Somewhat difficult,Yes,No,No,Some of them,No,Maybe,No,No
3,35,Male,No,Yes,Often,More than 1000,No,Yes,Don't know,Not sure,No,No,Yes,Very easy,No,No,Some of them,Some of them,No,Maybe,No,No
4,36,Male,No,No,Never,1-5,Yes,Yes,Don't know,Not sure,Don't know,Don't know,Don't know,Very easy,No,No,Some of them,Some of them,No,No,Don't know,No

# <font size = 3 color='Black'><b>2). Handling Missing Values</b>

In [15]:
#Check for missing values count in whole dataset
df.isnull().sum()

Age                            0
Gender                         0
self_employed                 18
family_history                 0
treatment                      0
work_interfere               236
no_employees                   0
remote_work                    0
tech_company                   0
benefits                       0
care_options                   0
wellness_program               0
seek_help                      0
anonymity                      0
leave                          0
mental_health_consequence      0
phys_health_consequence        0
coworkers                      0
supervisor                     0
mental_health_interview        0
phys_health_interview          0
mental_vs_physical             0
obs_consequence                0
dtype: int64

We can see there are Nan values in self_emplyed and work_interfere

As these are categorical variables, we'replace Nan with mode

In [16]:
df_test.isnull().sum()

Age                           0
Gender                        0
self_employed                 0
family_history                0
work_interfere               28
no_employees                  0
remote_work                   0
tech_company                  0
benefits                      0
care_options                  0
wellness_program              0
seek_help                     0
anonymity                     0
leave                         0
mental_health_consequence     0
phys_health_consequence       0
coworkers                     0
supervisor                    0
mental_health_interview       0
phys_health_interview         0
mental_vs_physical            0
obs_consequence               0
dtype: int64

There are missing values in work_interfere in test data

In [17]:
#we can use use fillna to fill the missing values with mean of the variable
#inplace is kept as true to work om only the missing values rather than the whole data and thereby reducing kernel load
df['self_employed'].fillna(df['self_employed'].mode()[0], inplace = True)

In [18]:
#df['work_interfere'].fillna(df['work_interfere'].mode()[0], inplace = True)
#as work_interfere is multi class variable so we added a new class for NaN values

In [19]:
df['work_interfere'].fillna("Don't Know", inplace = True)

In [20]:
df.isnull().sum()

Age                          0
Gender                       0
self_employed                0
family_history               0
treatment                    0
work_interfere               0
no_employees                 0
remote_work                  0
tech_company                 0
benefits                     0
care_options                 0
wellness_program             0
seek_help                    0
anonymity                    0
leave                        0
mental_health_consequence    0
phys_health_consequence      0
coworkers                    0
supervisor                   0
mental_health_interview      0
phys_health_interview        0
mental_vs_physical           0
obs_consequence              0
dtype: int64

In [21]:
df_test['work_interfere'].fillna("Don't Know", inplace = True)

In [22]:
df_test.isnull().sum()

Age                          0
Gender                       0
self_employed                0
family_history               0
work_interfere               0
no_employees                 0
remote_work                  0
tech_company                 0
benefits                     0
care_options                 0
wellness_program             0
seek_help                    0
anonymity                    0
leave                        0
mental_health_consequence    0
phys_health_consequence      0
coworkers                    0
supervisor                   0
mental_health_interview      0
phys_health_interview        0
mental_vs_physical           0
obs_consequence              0
dtype: int64

# <font size = 3 color='Black'><b>Handling Age variable</b>

The possible age range for employees can be considered between 17 to 65 and therefore we must replace/delete the values above or below this range

In [23]:
#calculating mean for values between 17 to 65
mean_age = int(df['Age'][(df['Age']<=65) & (df['Age']>=17)].mean())
mean_age_test = int(df_test['Age'][(df_test['Age']<=65) & (df_test['Age']>=17)].mean())

In [24]:
#Replacing values greater than 65 or lower than 17 with mean
df['Age'] = df['Age'].apply(lambda x: mean_age if (x>65 or x<17) else int(x))
df_test['Age']= df_test['Age'].apply(lambda x: mean_age_test if(x>65 or x<17) else int(x))

# <font size = 3 color='Black'><b>3). Converting Categorical/Discrete Var to Continuous Var</b>

We need to convert all variables except Age to discrete/numerical variables

1.) Gender

We need to manually encode the values to female(0),male(1) and others(2) as there are too many class for single labels

'''['Female' 'M' 'Male' 'male' 'female' 'm' 'Male-ish' 'maile' 'Trans-female'
 'Cis Female' 'F' 'something kinda male?' 'Cis Male' 'Woman' 'f' 'Mal'
 'Male (CIS)' 'queer/she/they' 'non-binary' 'Femake' 'woman' 'Make' 'Nah'
 'All' 'Enby' 'fluid' 'Genderqueer' 'Female ' 'Androgyne' 'Agender'
 'cis-female/femme' 'Guy (-ish) ^_^' 'male leaning androgynous' 'Male '
 'Man' 'Trans woman' 'msle' 'Neuter' 'Female (trans)' 'queer'
 'Female (cis)' 'Mail' 'cis male' 'A little about you' 'Malr']'''

In [25]:
df['Gender'] = df['Gender'].replace(('Female','female','F','Woman','f','Femake','woman','Female ','Cis Female','cis-female/femme','Female (cis)'),0)
df['Gender'] = df['Gender'].replace(('M','Male','male','m','Male-ish','maile','Mal','Make','Male ','Man','msle','Mail','Malr','Cis Male','Male (CIS)','cis male'),1)
df['Gender'] = df['Gender'].replace(('Trans-female','something kinda male?','queer/she/they','non-binary',
                                 'Nah','All','Enby','fluid','Genderqueer','Androgyne','Agender','Guy (-ish) ^_^',
                                  'male leaning androgynous','Trans woman','Neuter','Female (trans)','queer',
                                  'A little about you'),2)

In [26]:
# to check for the unique values of gender in test data
df_test['Gender'].unique()

array(['Male', 'female', 'Female', 'M', 'male', 'Male ', 'm', 'p', 'F',
       'Woman', 'femail', 'Cis Man',
       'ostensibly male, unsure what that really means', 'f'],
      dtype=object)

In [27]:
#Applying encoding to test data
df_test['Gender'] = df_test['Gender'].replace(('Female','female','F','Woman','f','femail'),0)
df_test['Gender'] = df_test['Gender'].replace(('M','Male','male','m','Male ','Cis Man'),1)
df_test['Gender'] = df_test['Gender'].replace(('p','ostensibly male, unsure what that really means'),2)

2.) no_employees

Unique values: ['6-25' 'More than 1000' '26-100' '100-500' '1-5' '500-1000']

In [28]:
df['no_employees'] = df['no_employees'].map({'1-5':0,'6-25':1,'26-100':2,'100-500':3,'500-1000':4,'More than 1000':5})

In [29]:
df_test['no_employees'] = df_test['no_employees'].map({'1-5':0,'6-25':1,'26-100':2,'100-500':3,'500-1000':4,'More than 1000':5})

In [30]:
df_test.dtypes

Age                           int64
Gender                        int64
self_employed                object
family_history               object
work_interfere               object
no_employees                  int64
remote_work                  object
tech_company                 object
benefits                     object
care_options                 object
wellness_program             object
seek_help                    object
anonymity                    object
leave                        object
mental_health_consequence    object
phys_health_consequence      object
coworkers                    object
supervisor                   object
mental_health_interview      object
phys_health_interview        object
mental_vs_physical           object
obs_consequence              object
dtype: object

3.)All other categorical values

In [32]:
#Reducing redundant class to a single class for 'leaves' variable
df['leave'] = df['leave'].replace(['Somewhat easy', 'Very easy'],'easy')
df_test['leave'] = df_test['leave'].replace(['Somewhat easy', 'Very easy'],'easy')

In [33]:
encode = LabelEncoder()
for i in df.columns:
    if df[i].dtype == 'object':
            df[i] = encode.fit_transform(df[i])

In [34]:
#To check if all the data types have been converted to int from object
df.dtypes

Age                          int64
Gender                       int64
self_employed                int32
family_history               int32
treatment                    int32
work_interfere               int32
no_employees                 int64
remote_work                  int32
tech_company                 int32
benefits                     int32
care_options                 int32
wellness_program             int32
seek_help                    int32
anonymity                    int32
leave                        int32
mental_health_consequence    int32
phys_health_consequence      int32
coworkers                    int32
supervisor                   int32
mental_health_interview      int32
phys_health_interview        int32
mental_vs_physical           int32
obs_consequence              int32
dtype: object

In [35]:
df.head()

,Age,Gender,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37,0,0,0,1,2,1,0,1,2,1,1,2,2,3,1,1,1,2,1,0,2,0
1,44,1,0,0,0,3,5,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0
2,32,1,0,0,0,3,1,0,1,1,0,1,1,0,1,1,1,2,2,2,2,1,0
3,31,1,0,1,1,2,2,0,1,1,2,1,1,1,1,2,2,1,0,0,0,1,1
4,31,1,0,0,0,1,3,1,1,2,0,0,0,0,0,1,1,1,2,2,2,0,0

In [36]:
df.tail()

,Age,Gender,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
1043,26,1,0,0,1,4,1,0,1,2,2,1,1,2,0,0,1,1,0,1,0,0,0
1044,29,0,0,0,1,2,5,0,0,2,2,1,1,0,0,0,1,1,0,1,2,1,1
1045,26,0,0,1,1,4,3,0,1,2,1,1,1,2,0,0,1,1,0,1,0,0,0
1046,33,1,0,1,1,4,1,0,1,1,1,1,1,0,3,1,1,1,2,1,1,0,0
1047,28,1,0,1,0,4,3,0,1,1,0,1,1,0,3,1,1,1,1,1,1,0,1

In [37]:
#encoding variables for data from test set
for i in df_test.columns:
    if df_test[i].dtype == 'object':
            df_test[i] = encode.fit_transform(df_test[i])

In [38]:
#To check if all the data types have been converted to int from object
df_test.dtypes

Age                          int64
Gender                       int64
self_employed                int32
family_history               int32
work_interfere               int32
no_employees                 int64
remote_work                  int32
tech_company                 int32
benefits                     int32
care_options                 int32
wellness_program             int32
seek_help                    int32
anonymity                    int32
leave                        int32
mental_health_consequence    int32
phys_health_consequence      int32
coworkers                    int32
supervisor                   int32
mental_health_interview      int32
phys_health_interview        int32
mental_vs_physical           int32
obs_consequence              int32
dtype: object

In [39]:
df_test.head()

,Age,Gender,self_employed,family_history,work_interfere,no_employees,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,39,1,1,1,4,0,1,1,1,2,2,2,2,1,1,1,2,2,1,0,2,1
1,26,0,0,1,4,5,0,1,2,2,1,1,0,0,1,1,1,2,1,0,1,1
2,23,0,0,1,4,2,0,0,1,0,1,1,0,1,2,1,0,1,1,0,1,0
3,35,1,0,1,2,5,0,1,0,1,1,1,2,3,1,1,1,1,1,0,1,0
4,36,1,0,0,1,0,1,1,0,1,0,0,0,3,1,1,1,1,1,1,0,0

### Creating x and y

In [40]:
# Target/Dependent variable is Treatment
x = df.loc[:, df.columns != 'treatment']
y = df.loc[:,'treatment']

In [41]:
print(x.shape)
print(y.shape)

(1048, 22)
(1048,)

### Scaling the data

In [42]:
scaler = StandardScaler()
#X = scaler.fit_transform(X)
#sepatate function for fit and transform
scaler.fit(x)
x = scaler.transform(x)

In [43]:
scaler.fit(df_test)
df_test = scaler.transform(df_test)

### Splitting the data into train and test set

Splitting train set to train and validation set as we already have our test set

In [44]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state = 10,stratify = y)

In [45]:
print("x_train:",x_train.shape)
print("x_test:",x_test.shape)
print("y_train:",y_train.shape)
print("y_test:",y_test.shape)

x_train: (733, 22)
x_test: (315, 22)
y_train: (733,)
y_test: (315,)

### Building Logistic Regression Model

In [46]:
#training the model
lr = LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [47]:
#Looking for coefficients value of output equation as logistic regression outputs a equation too
Coefficients = list(zip(df.columns[:-1],lr.coef_.ravel())) #ravel() is used to flatten the array
print(Coefficients)
print(lr.intercept_)

[('Age', 0.1896944061067346), ('Gender', -0.22318918272604368), ('self_employed', -0.0942058997162623), ('family_history', 0.5616608157176773), ('treatment', 1.4504827447163287), ('work_interfere', -0.14156972993623465), ('no_employees', -0.0002355909740508867), ('remote_work', -0.14078868191665192), ('tech_company', 0.2774712007956207), ('benefits', 0.3076093048413515), ('care_options', -0.03859578013071909), ('wellness_program', -0.18125656069073956), ('seek_help', 0.30425037493390344), ('anonymity', -0.11391851138333618), ('leave', -0.015661146489882684), ('mental_health_consequence', 0.08588907566261504), ('phys_health_consequence', 0.244996221762841), ('coworkers', -0.1507637535829961), ('supervisor', 0.06351873282039477), ('mental_health_interview', 0.22953759653606068), ('phys_health_interview', 0.0888748849525661), ('mental_vs_physical', 0.20009829907827476)]
[-0.14404415]

In [48]:
#outputting Probability matrix
prob = lr.predict_proba(x_test)
prob

array([[0.87286481, 0.12713519],
       [0.62527109, 0.37472891],
       [0.27669703, 0.72330297],
       [0.88572324, 0.11427676],
       [0.24106397, 0.75893603],
       [0.51612181, 0.48387819],
       [0.58499005, 0.41500995],
       [0.91269501, 0.08730499],
       [0.29175169, 0.70824831],
       [0.98584205, 0.01415795],
       [0.66700094, 0.33299906],
       [0.45849488, 0.54150512],
       [0.03311294, 0.96688706],
       [0.07240624, 0.92759376],
       [0.15725009, 0.84274991],
       [0.19918978, 0.80081022],
       [0.07933   , 0.92067   ],
       [0.82168191, 0.17831809],
       [0.95435078, 0.04564922],
       [0.92531586, 0.07468414],
       [0.85870274, 0.14129726],
       [0.94467504, 0.05532496],
       [0.70997631, 0.29002369],
       [0.12666241, 0.87333759],
       [0.29801177, 0.70198823],
       [0.01176998, 0.98823002],
       [0.09765669, 0.90234331],
       [0.61732189, 0.38267811],
       [0.61818767, 0.38181233],
       [0.04927964, 0.95072036],
       [0.22200177, 0.77799823],
       [0.23067266, 0.76932734],
       [0.48974565, 0.51025435],
       [0.22540246, 0.77459754],
       [0.73274218, 0.26725782],
       [0.97084818, 0.02915182],
       [0.32791412, 0.67208588],
       [0.96227689, 0.03772311],
       [0.957871  , 0.042129  ],
       [0.86321548, 0.13678452],
       [0.27902567, 0.72097433],
       [0.7975243 , 0.2024757 ],
       [0.43106417, 0.56893583],
       [0.28407436, 0.71592564],
       [0.96821992, 0.03178008],
       [0.97577511, 0.02422489],
       [0.8453851 , 0.1546149 ],
       [0.72616074, 0.27383926],
       [0.01139865, 0.98860135],
       [0.89199948, 0.10800052],
       [0.03840243, 0.96159757],
       [0.93811329, 0.06188671],
       [0.78896199, 0.21103801],
       [0.78476717, 0.21523283],
       [0.92156133, 0.07843867],
       [0.11566358, 0.88433642],
       [0.18345635, 0.81654365],
       [0.07919008, 0.92080992],
       [0.34874901, 0.65125099],
       [0.87857617, 0.12142383],
       [0.9278751 , 0.0721249 ],
       [0.87558635, 0.12441365],
       [0.84014825, 0.15985175],
       [0.36632848, 0.63367152],
       [0.94370664, 0.05629336],
       [0.8850187 , 0.1149813 ],
       [0.94362027, 0.05637973],
       [0.34134123, 0.65865877],
       [0.36099337, 0.63900663],
       [0.84987067, 0.15012933],
       [0.19326678, 0.80673322],
       [0.13978857, 0.86021143],
       [0.23619044, 0.76380956],
       [0.981016  , 0.018984  ],
       [0.03070945, 0.96929055],
       [0.92453831, 0.07546169],
       [0.05362159, 0.94637841],
       [0.0268087 , 0.9731913 ],
       [0.04920642, 0.95079358],
       [0.1194969 , 0.8805031 ],
       [0.1632042 , 0.8367958 ],
       [0.9112554 , 0.0887446 ],
       [0.86343108, 0.13656892],
       [0.13231789, 0.86768211],
       [0.3241908 , 0.6758092 ],
       [0.87329231, 0.12670769],
       [0.9786181 , 0.0213819 ],
       [0.81295211, 0.18704789],
       [0.81431569, 0.18568431],
       [0.487316  , 0.512684  ],
       [0.9341784 , 0.0658216 ],
       [0.47455867, 0.52544133],
       [0.89471805, 0.10528195],
       [0.94487367, 0.05512633],
       [0.64266902, 0.35733098],
       [0.93226973, 0.06773027],
       [0.9487541 , 0.0512459 ],
       [0.29520916, 0.70479084],
       [0.06654847, 0.93345153],
       [0.18606311, 0.81393689],
       [0.4437992 , 0.5562008 ],
       [0.35434109, 0.64565891],
       [0.1042179 , 0.8957821 ],
       [0.12697722, 0.87302278],
       [0.21579398, 0.78420602],
       [0.9614046 , 0.0385954 ],
       [0.91984623, 0.08015377],
       [0.31906559, 0.68093441],
       [0.90491966, 0.09508034],
       [0.1130505 , 0.8869495 ],
       [0.29659593, 0.70340407],
       [0.02730176, 0.97269824],
       [0.66787693, 0.33212307],
       [0.8180159 , 0.1819841 ],
       [0.13530188, 0.86469812],
       [0.8239638 , 0.1760362 ],
       [0.18359234, 0.81640766],
       [0.95637795, 0.04362205],
       [0.21352435, 0.78647565],
       [0.71244964, 0.28755036],
       [0.93790203, 0.06209797],
       [0.40261198, 0.59738802],
       [0.07465742, 0.92534258],
       [0.76996683, 0.23003317],
       [0.16800914, 0.83199086],
       [0.79030319, 0.20969681],
       [0.91891941, 0.08108059],
       [0.84557976, 0.15442024],
       [0.97698334, 0.02301666],
       [0.09227548, 0.90772452],
       [0.0332532 , 0.9667468 ],
       [0.15670903, 0.84329097],
       [0.91452315, 0.08547685],
       [0.12666058, 0.87333942],
       [0.83644233, 0.16355767],
       [0.66573695, 0.33426305],
       [0.91560625, 0.08439375],
       [0.73795725, 0.26204275],
       [0.27857455, 0.72142545],
       [0.79980194, 0.20019806],
       [0.73886934, 0.26113066],
       [0.01298259, 0.98701741],
       [0.58642921, 0.41357079],
       [0.96400027, 0.03599973],
       [0.89461079, 0.10538921],
       [0.93089999, 0.06910001],
       [0.96250982, 0.03749018],
       [0.88536059, 0.11463941],
       [0.75405643, 0.24594357],
       [0.10949218, 0.89050782],
       [0.06756159, 0.93243841],
       [0.90063985, 0.09936015],
       [0.09988706, 0.90011294],
       [0.01973399, 0.98026601],
       [0.23397453, 0.76602547],
       [0.86634663, 0.13365337],
       [0.96003874, 0.03996126],
       [0.01364084, 0.98635916],
       [0.95950021, 0.04049979],
       [0.02248615, 0.97751385],
       [0.11803347, 0.88196653],
       [0.52270902, 0.47729098],
       [0.80674687, 0.19325313],
       [0.84960831, 0.15039169],
       [0.94894011, 0.05105989],
       [0.96537056, 0.03462944],
       [0.1268135 , 0.8731865 ],
       [0.26848824, 0.73151176],
       [0.55571584, 0.44428416],
       [0.02546504, 0.97453496],
       [0.84212234, 0.15787766],
       [0.29656001, 0.70343999],
       [0.34347268, 0.65652732],
       [0.07344566, 0.92655434],
       [0.1562727 , 0.8437273 ],
       [0.3915882 , 0.6084118 ],
       [0.17690023, 0.82309977],
       [0.20134374, 0.79865626],
       [0.61524716, 0.38475284],
       [0.24554427, 0.75445573],
       [0.79187135, 0.20812865],
       [0.07404481, 0.92595519],
       [0.52386536, 0.47613464],
       [0.91385365, 0.08614635],
       [0.31433009, 0.68566991],
       [0.08621866, 0.91378134],
       [0.56584087, 0.43415913],
       [0.94253547, 0.05746453],
       [0.94839875, 0.05160125],
       [0.23099188, 0.76900812],
       [0.82968386, 0.17031614],
       [0.88413949, 0.11586051],
       [0.88302677, 0.11697323],
       [0.03234039, 0.96765961],
       [0.86889205, 0.13110795],
       [0.73288561, 0.26711439],
       [0.05983627, 0.94016373],
       [0.41528009, 0.58471991],
       [0.44373671, 0.55626329],
       [0.96405071, 0.03594929],
       [0.95434915, 0.04565085],
       [0.07435099, 0.92564901],
       [0.11824628, 0.88175372],
       [0.54483188, 0.45516812],
       [0.04863071, 0.95136929],
       [0.87561039, 0.12438961],
       [0.43760794, 0.56239206],
       [0.1268724 , 0.8731276 ],
       [0.20286905, 0.79713095],
       [0.9640409 , 0.0359591 ],
       [0.96033212, 0.03966788],
       [0.39452468, 0.60547532],
       [0.27762033, 0.72237967],
       [0.12078029, 0.87921971],
       [0.98545922, 0.01454078],
       [0.77075679, 0.22924321],
       [0.07026542, 0.92973458],
       [0.56894842, 0.43105158],
       [0.07385408, 0.92614592],
       [0.29195076, 0.70804924],
       [0.88962638, 0.11037362],
       [0.89792692, 0.10207308],
       [0.36806949, 0.63193051],
       [0.08167116, 0.91832884],
       [0.37720265, 0.62279735],
       [0.06451945, 0.93548055],
       [0.93415334, 0.06584666],
       [0.11056255, 0.88943745],
       [0.50960357, 0.49039643],
       [0.97422366, 0.02577634],
       [0.2353126 , 0.7646874 ],
       [0.85133664, 0.14866336],
       [0.49390114, 0.50609886],
       [0.88691081, 0.11308919],
       [0.56013204, 0.43986796],
       [0.37788156, 0.62211844],
       [0.95520843, 0.04479157],
       [0.37553529, 0.62446471],
       [0.89417341, 0.10582659],
       [0.06623536, 0.93376464],
       [0.96309911, 0.03690089],
       [0.02984927, 0.97015073],
       [0.85619424, 0.14380576],
       [0.11843199, 0.88156801],
       [0.95859993, 0.04140007],
       [0.09830337, 0.90169663],
       [0.01655454, 0.98344546],
       [0.04977541, 0.95022459],
       [0.81387732, 0.18612268],
       [0.58923742, 0.41076258],
       [0.44179944, 0.55820056],
       [0.88927088, 0.11072912],
       [0.31885431, 0.68114569],
       [0.91895349, 0.08104651],
       [0.91996703, 0.08003297],
       [0.94132257, 0.05867743],
       [0.47738672, 0.52261328],
       [0.90521462, 0.09478538],
       [0.27570172, 0.72429828],
       [0.97764009, 0.02235991],
       [0.91725559, 0.08274441],
       [0.51397543, 0.48602457],
       [0.305146  , 0.694854  ],
       [0.15231003, 0.84768997],
       [0.07452481, 0.92547519],
       [0.23875796, 0.76124204],
       [0.50848284, 0.49151716],
       [0.95612274, 0.04387726],
       [0.4354288 , 0.5645712 ],
       [0.02476643, 0.97523357],
       [0.16987857, 0.83012143],
       [0.34112587, 0.65887413],
       [0.98103526, 0.01896474],
       [0.36680166, 0.63319834],
       [0.02908942, 0.97091058],
       [0.6030505 , 0.3969495 ],
       [0.96814306, 0.03185694],
       [0.96635067, 0.03364933],
       [0.96942236, 0.03057764],
       [0.35360818, 0.64639182],
       [0.87262882, 0.12737118],
       [0.76135235, 0.23864765],
       [0.1197386 , 0.8802614 ],
       [0.3202979 , 0.6797021 ],
       [0.18733798, 0.81266202],
       [0.18472917, 0.81527083],
       [0.90622228, 0.09377772],
       [0.05770017, 0.94229983],
       [0.21753488, 0.78246512],
       [0.88502107, 0.11497893],
       [0.2156749 , 0.7843251 ],
       [0.65948238, 0.34051762],
       [0.16150926, 0.83849074],
       [0.12698509, 0.87301491],
       [0.98194488, 0.01805512],
       [0.87802768, 0.12197232],
       [0.33981539, 0.66018461],
       [0.15876791, 0.84123209],
       [0.86390582, 0.13609418],
       [0.15164389, 0.84835611],
       [0.06360748, 0.93639252],
       [0.51228689, 0.48771311],
       [0.89245651, 0.10754349],
       [0.22809534, 0.77190466],
       [0.12305774, 0.87694226],
       [0.20822968, 0.79177032],
       [0.39690934, 0.60309066],
       [0.62459265, 0.37540735],
       [0.04374238, 0.95625762],
       [0.82071855, 0.17928145],
       [0.35764883, 0.64235117],
       [0.94088548, 0.05911452],
       [0.80310438, 0.19689562],
       [0.06905988, 0.93094012],
       [0.95149873, 0.04850127]])

In [49]:
#Predicting values
y_pred = lr.predict(x_test)

### Evaluation of model

In [50]:
cfm = confusion_matrix(y_test,y_pred)
print("Confusion Matrix: ")
print(cfm)

acc = accuracy_score(y_test,y_pred)
print("accuracy score",acc)

print('classification report : ')
print(classification_report(y_test,y_pred))

Confusion Matrix:
[[134  27]
 [ 24 130]]
accuracy score 0.8380952380952381
classification report :
              precision    recall  f1-score   support

           0       0.85      0.83      0.84       161
           1       0.83      0.84      0.84       154

    accuracy                           0.84       315
   macro avg       0.84      0.84      0.84       315
weighted avg       0.84      0.84      0.84       315

### Fine Tuning the model

#### 1.) Adjusting Threshold

Using Ridge Regression:

In [51]:
#to loop through various values of threshold and check which one gives least error(wrong predictions)
for i in np.arange(0.4,0.61,0.01):
    pred = np.where(prob[:,1]>i,1,0)
    cfm = confusion_matrix(y_test,pred)
    err = cfm[1,0]+cfm[0,1]
    print("Error for threshold,",i," : ",err, "and Type II error :",cfm[1,0],"and Type I error :",cfm[0,1])

Error for threshold, 0.4  :  46 and Type II error : 14 and Type I error : 32
Error for threshold, 0.41000000000000003  :  46 and Type II error : 14 and Type I error : 32
Error for threshold, 0.42000000000000004  :  47 and Type II error : 16 and Type I error : 31
Error for threshold, 0.43000000000000005  :  47 and Type II error : 16 and Type I error : 31
Error for threshold, 0.44000000000000006  :  46 and Type II error : 17 and Type I error : 29
Error for threshold, 0.45000000000000007  :  45 and Type II error : 17 and Type I error : 28
Error for threshold, 0.4600000000000001  :  46 and Type II error : 18 and Type I error : 28
Error for threshold, 0.4700000000000001  :  46 and Type II error : 18 and Type I error : 28
Error for threshold, 0.4800000000000001  :  48 and Type II error : 20 and Type I error : 28
Error for threshold, 0.4900000000000001  :  49 and Type II error : 22 and Type I error : 27
Error for threshold, 0.5000000000000001  :  51 and Type II error : 24 and Type I error : 27
Error for threshold, 0.5100000000000001  :  52 and Type II error : 25 and Type I error : 27
Error for threshold, 0.5200000000000001  :  54 and Type II error : 27 and Type I error : 27
Error for threshold, 0.5300000000000001  :  52 and Type II error : 27 and Type I error : 25
Error for threshold, 0.5400000000000001  :  52 and Type II error : 27 and Type I error : 25
Error for threshold, 0.5500000000000002  :  53 and Type II error : 28 and Type I error : 25
Error for threshold, 0.5600000000000002  :  54 and Type II error : 30 and Type I error : 24
Error for threshold, 0.5700000000000002  :  55 and Type II error : 32 and Type I error : 23
Error for threshold, 0.5800000000000002  :  55 and Type II error : 32 and Type I error : 23
Error for threshold, 0.5900000000000002  :  56 and Type II error : 33 and Type I error : 23
Error for threshold, 0.6000000000000002  :  57 and Type II error : 34 and Type I error : 23

We can see we are getting lesser Type 2 error at threshold 0.44 so we'll try prdeicting the value using that threshold and generate evaluation metrics

In [52]:
#prob is the probability matrix that we genearted above
y_pred_t = [1 if i>0.44 else 0 for i in prob[:,1]]

In [53]:
cfm = confusion_matrix(y_test,y_pred_t)
print("Confusion Matrix: ")
print(cfm)

acc = accuracy_score(y_test,y_pred_t)
print("accuracy score",acc)

print('classification report : ')
print(classification_report(y_test,y_pred_t))

Confusion Matrix:
[[132  29]
 [ 17 137]]
accuracy score 0.8539682539682539
classification report :
              precision    recall  f1-score   support

           0       0.89      0.82      0.85       161
           1       0.83      0.89      0.86       154

    accuracy                           0.85       315
   macro avg       0.86      0.85      0.85       315
weighted avg       0.86      0.85      0.85       315

We can conclude following from above evaluation:

    Recall for class 0 has been decresed by 1 unit but f1-score is  increased by 1 unit
    
    Recall for class 1 has been increased by 6 units and f1-score is  increased by 2 units
    
    Accuracy score has improved a little bit from 0.838 to 0.857

Therefore, we'll use the logistic regression model having threshold as 0.44

In [54]:
log_adj = LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

### SGD Classification

In [55]:
sgd = SGDClassifier(loss = 'log', random_state = 10, 
                    learning_rate ='constant', eta0 = 0.00001,
                   max_iter= 1000,shuffle = True,
                   early_stopping = True,n_iter_no_change = 5)
sgd.fit(x_train,y_train)
y_sgd = sgd.predict(x_test)

In [56]:
cfm = confusion_matrix(y_test,y_sgd)
print("Confusion Matrix: ")
print(cfm)

acc = accuracy_score(y_test,y_sgd)
print("accuracy score",acc)

print('classification report : ')
print(classification_report(y_test,y_sgd))

Confusion Matrix:
[[129  32]
 [ 34 120]]
accuracy score 0.7904761904761904
classification report :
              precision    recall  f1-score   support

           0       0.79      0.80      0.80       161
           1       0.79      0.78      0.78       154

    accuracy                           0.79       315
   macro avg       0.79      0.79      0.79       315
weighted avg       0.79      0.79      0.79       315

As we can see, accuracy score and f1-score for both the classes are lower than sklearn model so we'll not use this

### Recursive Feature Elimination(RFE)

In [61]:
col = df.loc[:,df.columns != 'treatment']
colname = col.columns
#lr is the our fitted model using LogisticRegression
rfe = RFE(lr,12)

#storing this into an object because we want to use some functions using that object 
model_rfe = rfe.fit(x_train,y_train) 

# total number features left
print("Number of Features left: ",model_rfe.n_features_)

#will give true false values to the columns, true if var exist in final model
print("Selected Features:")
print(list(zip(colname,model_rfe.support_)))

#also we can check ranking column name wise, to see which var is eliminated at which level,
#1 means present in final model, highest number rank is eliminated first
print("Feature Ranking: ")
print(list(zip(colname,model_rfe.ranking_)))

Number of Features left:  12
Selected Features:
[('Age', True), ('Gender', True), ('self_employed', False), ('family_history', True), ('work_interfere', True), ('no_employees', False), ('remote_work', False), ('tech_company', False), ('benefits', True), ('care_options', True), ('wellness_program', False), ('seek_help', True), ('anonymity', True), ('leave', False), ('mental_health_consequence', False), ('phys_health_consequence', False), ('coworkers', True), ('supervisor', True), ('mental_health_interview', False), ('phys_health_interview', True), ('mental_vs_physical', False), ('obs_consequence', True)]
Feature Ranking:
[('Age', 1), ('Gender', 1), ('self_employed', 6), ('family_history', 1), ('work_interfere', 1), ('no_employees', 3), ('remote_work', 11), ('tech_company', 2), ('benefits', 1), ('care_options', 1), ('wellness_program', 9), ('seek_help', 1), ('anonymity', 1), ('leave', 4), ('mental_health_consequence', 10), ('phys_health_consequence', 5), ('coworkers', 1), ('supervisor', 1), ('mental_health_interview', 8), ('phys_health_interview', 1), ('mental_vs_physical', 7), ('obs_consequence', 1)]

In [62]:
#predicting values using RFE model
y_rfe = model_rfe.predict(x_test)

In [63]:
cfm = confusion_matrix(y_test,y_rfe)
print("Confusion Matrix: ")
print(cfm)

acc = accuracy_score(y_test,y_rfe)
print("accuracy score",acc)

print('classification report : ')
print(classification_report(y_test,y_rfe))

Confusion Matrix:
[[136  25]
 [ 27 127]]
accuracy score 0.834920634920635
classification report :
              precision    recall  f1-score   support

           0       0.83      0.84      0.84       161
           1       0.84      0.82      0.83       154

    accuracy                           0.83       315
   macro avg       0.83      0.83      0.83       315
weighted avg       0.83      0.83      0.83       315

We can see that the results are best when we build model over 12 variables selected using RFE

### K-Fold Cross Validation

In [64]:
#For evaluating Logistic Regression Model lr

kfold_cv = KFold(n_splits = 10, random_state = 10)

result = cross_val_score(estimator = lr,X= x_train,y=y_train, cv = kfold_cv)

print(result)
print(result.mean())

[0.78378378 0.85135135 0.7972973  0.76712329 0.82191781 0.84931507
 0.80821918 0.75342466 0.80821918 0.79452055]
0.8035172158459829

As we can see, the mean of accuracy of kfolds is slightly greater than the accuracy score of lr which was 0.695

In [65]:
#For evaluating SGD model

kfold_cv = KFold(n_splits = 10, random_state = 10)

result = cross_val_score(estimator = sgd,X= x_train,y=y_train, cv = kfold_cv)

print(result)
print(result.mean())

[0.66216216 0.86486486 0.78378378 0.71232877 0.79452055 0.79452055
 0.80821918 0.75342466 0.69863014 0.75342466]
0.7625879303961496

As we can see, the mean of accuracy of kfolds is slightly greater than the accuracy score of sgd which was 0.676

# <font size = 5 color='Black'><b>Therefore, we can conclude that the best model is the one built using Logistic  Regression<b>

Predicting values for actual test data

In [67]:
#lr = LogisticRegression()
#lr.fit(x_train,y_train)
prob_test = lr.predict_proba(df_test)
prob_test

array([[0.04534142, 0.95465858],
       [0.06131426, 0.93868574],
       [0.20614177, 0.79385823],
       [0.62022864, 0.37977136],
       [0.91084696, 0.08915304],
       [0.60546166, 0.39453834],
       [0.03824112, 0.96175888],
       [0.96927692, 0.03072308],
       [0.96789283, 0.03210717],
       [0.48044387, 0.51955613],
       [0.20251929, 0.79748071],
       [0.84951589, 0.15048411],
       [0.35856143, 0.64143857],
       [0.92279604, 0.07720396],
       [0.92526633, 0.07473367],
       [0.22117079, 0.77882921],
       [0.46592636, 0.53407364],
       [0.93274744, 0.06725256],
       [0.88902939, 0.11097061],
       [0.73752149, 0.26247851],
       [0.98232704, 0.01767296],
       [0.32771826, 0.67228174],
       [0.3598264 , 0.6401736 ],
       [0.31638916, 0.68361084],
       [0.96480669, 0.03519331],
       [0.2761859 , 0.7238141 ],
       [0.04564294, 0.95435706],
       [0.11363525, 0.88636475],
       [0.18026769, 0.81973231],
       [0.064083  , 0.935917  ],
       [0.43290643, 0.56709357],
       [0.36475563, 0.63524437],
       [0.67395499, 0.32604501],
       [0.54368555, 0.45631445],
       [0.45608425, 0.54391575],
       [0.06364763, 0.93635237],
       [0.9687753 , 0.0312247 ],
       [0.42882311, 0.57117689],
       [0.70117216, 0.29882784],
       [0.15516267, 0.84483733],
       [0.03289556, 0.96710444],
       [0.85990759, 0.14009241],
       [0.53292541, 0.46707459],
       [0.37653332, 0.62346668],
       [0.14679853, 0.85320147],
       [0.37947218, 0.62052782],
       [0.13250162, 0.86749838],
       [0.42727866, 0.57272134],
       [0.08125643, 0.91874357],
       [0.96505467, 0.03494533],
       [0.88399347, 0.11600653],
       [0.96325462, 0.03674538],
       [0.25384806, 0.74615194],
       [0.27332217, 0.72667783],
       [0.10688306, 0.89311694],
       [0.90532769, 0.09467231],
       [0.68399   , 0.31601   ],
       [0.46972024, 0.53027976],
       [0.28044518, 0.71955482],
       [0.63437493, 0.36562507],
       [0.90124349, 0.09875651],
       [0.05543977, 0.94456023],
       [0.57202508, 0.42797492],
       [0.94076255, 0.05923745],
       [0.18119603, 0.81880397],
       [0.94781766, 0.05218234],
       [0.14098188, 0.85901812],
       [0.92014424, 0.07985576],
       [0.1639873 , 0.8360127 ],
       [0.17593962, 0.82406038],
       [0.86172671, 0.13827329],
       [0.33226746, 0.66773254],
       [0.36360244, 0.63639756],
       [0.91514008, 0.08485992],
       [0.45517061, 0.54482939],
       [0.92299657, 0.07700343],
       [0.4653067 , 0.5346933 ],
       [0.40947219, 0.59052781],
       [0.1892958 , 0.8107042 ],
       [0.14096208, 0.85903792],
       [0.93730426, 0.06269574],
       [0.01805294, 0.98194706],
       [0.966074  , 0.033926  ],
       [0.09022195, 0.90977805],
       [0.51336155, 0.48663845],
       [0.51336155, 0.48663845],
       [0.37195593, 0.62804407],
       [0.20039327, 0.79960673],
       [0.94933891, 0.05066109],
       [0.30060299, 0.69939701],
       [0.44951408, 0.55048592],
       [0.49612776, 0.50387224],
       [0.5478833 , 0.4521167 ],
       [0.46268604, 0.53731396],
       [0.58371752, 0.41628248],
       [0.76005544, 0.23994456],
       [0.22060007, 0.77939993],
       [0.10261195, 0.89738805],
       [0.17530369, 0.82469631],
       [0.48727095, 0.51272905],
       [0.58703367, 0.41296633],
       [0.15355256, 0.84644744],
       [0.95711941, 0.04288059],
       [0.31220544, 0.68779456],
       [0.11494399, 0.88505601],
       [0.64805305, 0.35194695],
       [0.9611288 , 0.0388712 ],
       [0.92136963, 0.07863037],
       [0.81317451, 0.18682549],
       [0.27711521, 0.72288479],
       [0.93153034, 0.06846966],
       [0.28723964, 0.71276036],
       [0.89511587, 0.10488413],
       [0.97711661, 0.02288339],
       [0.36115826, 0.63884174],
       [0.27348336, 0.72651664],
       [0.12664825, 0.87335175],
       [0.09439352, 0.90560648],
       [0.92662575, 0.07337425],
       [0.87326542, 0.12673458],
       [0.10140532, 0.89859468],
       [0.97984022, 0.02015978],
       [0.98282608, 0.01717392],
       [0.01807486, 0.98192514],
       [0.20413047, 0.79586953],
       [0.67765192, 0.32234808],
       [0.91549373, 0.08450627],
       [0.37977884, 0.62022116],
       [0.8507361 , 0.1492639 ],
       [0.41784792, 0.58215208],
       [0.30948145, 0.69051855],
       [0.06550846, 0.93449154],
       [0.0274023 , 0.9725977 ],
       [0.60309294, 0.39690706],
       [0.05076523, 0.94923477],
       [0.70214125, 0.29785875],
       [0.83991104, 0.16008896],
       [0.42423292, 0.57576708],
       [0.12590808, 0.87409192],
       [0.93917182, 0.06082818],
       [0.02079979, 0.97920021],
       [0.04186066, 0.95813934],
       [0.14705611, 0.85294389],
       [0.95318898, 0.04681102],
       [0.85060177, 0.14939823],
       [0.97123538, 0.02876462],
       [0.04545595, 0.95454405],
       [0.48867739, 0.51132261],
       [0.90248596, 0.09751404],
       [0.71633861, 0.28366139],
       [0.97889399, 0.02110601],
       [0.83371595, 0.16628405],
       [0.30210126, 0.69789874],
       [0.94989874, 0.05010126],
       [0.99232692, 0.00767308],
       [0.81806856, 0.18193144],
       [0.59410302, 0.40589698],
       [0.54632287, 0.45367713],
       [0.31517541, 0.68482459],
       [0.57014453, 0.42985547],
       [0.29154788, 0.70845212],
       [0.95064527, 0.04935473],
       [0.82871818, 0.17128182],
       [0.12226442, 0.87773558],
       [0.46008309, 0.53991691],
       [0.52044651, 0.47955349],
       [0.97732873, 0.02267127],
       [0.76572629, 0.23427371],
       [0.77003982, 0.22996018],
       [0.97732873, 0.02267127],
       [0.30527625, 0.69472375],
       [0.55383548, 0.44616452],
       [0.08617043, 0.91382957],
       [0.2579136 , 0.7420864 ],
       [0.95574738, 0.04425262],
       [0.10665253, 0.89334747],
       [0.43328133, 0.56671867],
       [0.95619699, 0.04380301],
       [0.43441712, 0.56558288],
       [0.26515064, 0.73484936],
       [0.95142492, 0.04857508],
       [0.0690218 , 0.9309782 ],
       [0.52721057, 0.47278943],
       [0.03404535, 0.96595465],
       [0.569632  , 0.430368  ],
       [0.69473897, 0.30526103],
       [0.57701421, 0.42298579],
       [0.86673301, 0.13326699],
       [0.14241337, 0.85758663],
       [0.30679943, 0.69320057],
       [0.47235683, 0.52764317],
       [0.17128419, 0.82871581],
       [0.88257741, 0.11742259],
       [0.80038993, 0.19961007],
       [0.16739369, 0.83260631],
       [0.92712386, 0.07287614],
       [0.42676403, 0.57323597],
       [0.93993499, 0.06006501],
       [0.72687883, 0.27312117],
       [0.08338747, 0.91661253],
       [0.05407537, 0.94592463],
       [0.73211278, 0.26788722],
       [0.35138784, 0.64861216],
       [0.0543634 , 0.9456366 ],
       [0.60998468, 0.39001532],
       [0.98372114, 0.01627886],
       [0.24778799, 0.75221201],
       [0.09504075, 0.90495925],
       [0.90684507, 0.09315493],
       [0.02996955, 0.97003045]])

In [68]:
pred_test =[1 if i>0.44 else 0 for i in prob_test[:,1]]

In [77]:
output = pd.DataFrame()
output['treatment'] = pred_test
output['treatment'] = output['treatment'].map({1:"Yes",0:"No"})

In [79]:
output.to_csv("output.csv",header=True,index=False)